//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments
    {
        public int AppointmentID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<System.TimeSpan> AppointmentTime { get; set; }
        public string Reason { get; set; }
        public string Status { get; set; }
        public Nullable<int> RoomID { get; set; }
    
        public virtual Doctors Doctors { get; set; }
        public virtual Patients Patients { get; set; }
        public virtual Rooms Rooms { get; set; }
    }
}
