//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNO
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalHistory
    {
        public int HistoryID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string Details { get; set; }
    
        public virtual Patients Patients { get; set; }
    }
}
